language: node_js
node_js:
  - "10"
  - "12"
  - "14"
script: 'npm run coverage'
after_success: 'npm run coveralls'

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "npm run build && npx semantic-release"
